import Head from 'next/head'
import { initializeApp } from 'firebase/app'
import { getFirestore } from 'firebase/firestore'
import { getAuth } from 'firebase/auth'
import App from '../components/App'



const firebaseConfig = { 
  apiKey: "AIzaSyC1kgNdh0kDMxL7NBVWosO6TewMiPDBUog",
  authDomain: "to-do-list-reymondar.firebaseapp.com",
  projectId: "to-do-list-reymondar",
  storageBucket: "to-do-list-reymondar.appspot.com",
  messagingSenderId: "656736266312",
  appId: "1:656736266312:web:1a82bdf7e1650a0aa6907d"
}

const app = initializeApp(firebaseConfig)
const db = getFirestore(app)

const auth = getAuth(app)


auth.languageCode = 'es'

export default function Home() {
  
  
  return (
    <>
      <Head>
        <title>Evernote</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='h-screen'>
        <App />
      </main>
    </>
  )
}

export { app , db , auth };